"""update user schema

Revision ID: eb58833c473a
Revises: ed30a8f17cf4
Create Date: 2026-03-25 12:42:08.856309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb58833c473a'
down_revision: Union[str, None] = 'ed30a8f17cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('uq_users_foo_bar'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.drop_column('users', 'bar')
    op.drop_column('users', 'foo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('foo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('bar', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_foo_bar'), 'users', ['foo', 'bar'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
